import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Modal from '../components/Modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Proj. Mgmt App',
  description: 'Generated by Mihir Upadhyay',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[url('../public/assets/landscape.jpg')] bg-contain"> 
        
        <Modal />
        {children}
      </body>
    </html>
  )
}
